version: '3.8'

# 나스 서버 프로덕션용 설정
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - auto_stock_backend:latest
    image: auto_stock_backend:latest
    container_name: auto_stock_backend_prod
    ports:
      - "8000:8000"
    volumes:
      # 로그와 데이터는 호스트에 보관
      - /volume1/docker/auto_stock/logs:/app/logs
      - /volume1/docker/auto_stock/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      - ENV=production
    env_file:
      - .env.production
    restart: always
    networks:
      - auto_stock_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

networks:
  auto_stock_network:
    external: true