version: '3.3'  # 시놀로지 Container Manager 호환

services:
  # 키움 자동매매 백엔드 서버
  backend:
    build: ./backend
    container_name: auto-stock-backend
    ports:
      - "8080:8001"  # NAS 8080 포트를 컨테이너 8001로 매핑
    env_file:
      - .env
    environment:
      # Python 설정
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      # 로깅
      - LOG_LEVEL=INFO
    volumes:
      # 시놀로지 경로 설정
      - ./backend:/app
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "openapi.kiwoom.com:211.115.74.81"
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  trading-network:
    driver: bridge